### ISSUE TITLE
ValueError when using default self

### ISSUE THREAD

**Issue by IISuperluminaLII** [lucas-emery/rocket-league-gym#13]
@lucas-emery 
@AechPro 
I have a simple example env to play with self enabled, but I am getting the following error.

 ```ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 1.```

This is the code that I am testing

```
env = rlgym.make("default self", reward_fn=CombinedReward(reward_functions=rewards))
# check_env(env, warn=True, skip_render_check=False)
model = PPO("MlpPolicy", env, verbose=1)
model.learn(total_timesteps=int(1e6))
```
This is the entire traceback of the workflow.
```
Traceback (most recent call last):
  File "rltestbot.py", line 19, in <module>
    model.learn(total_timesteps=int(1e6))
  File "lib\site-packages\stable_baselines3\ppo\ppo.py", line 289, in learn
    reset_num_timesteps=reset_num_timesteps,
  File "lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 220, in learn
    total_timesteps, eval_env, callback, eval_freq, n_eval_episodes, eval_log_path, reset_num_timesteps, tb_log_name
  File "lib\site-packages\stable_baselines3\common\base_class.py", line 379, in _setup_learn
    self._last_obs = self.env.reset()
  File "lib\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py", line 62, in reset
    self._save_obs(env_idx, obs)
  File "lib\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py", line 92, in _save_obs
    self.buf_obs[key][env_idx] = obs
ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 1.
```
Anyone know how to resolve this?

**Comment by AechPro** [comment]
It looks like you are attempting to train a self-play agent with the stable_baselines3 implementation of PPO. This learning algorithm does not natively support self-play. We do enable this functionality with our new wrappers, but they have not been appropriately documented yet.

**Comment by IISuperluminaLII** [comment]
Do you recommend me use the pettingzoo wrapper?

**Comment by IISuperluminaLII** [comment]
nvm its the vecenv wrapper that im interested in lol
